name: Build and Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version number"
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      releaseVersion: ${{ inputs.releaseVersion }}
      workingDirectory: ${{github.workspace}}/vendordep
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - run: chmod +x gradlew
        working-directory: ${{ env.workingDirectory }}
      - name: Install roboRio toolchain
        run: ./gradlew installRoboRioToolchain
        working-directory: ${{ env.workingDirectory }}
      - name: Build vendordep
        run: ./gradlew build
        working-directory: ${{ env.workingDirectory }}
      - name: Publish vendordep
        run: ./gradlew publish
        working-directory: ${{ env.workingDirectory }}
#      - name: Create Vendor JSON Repo PR
#        uses: wpilibsuite/vendor-json-repo/.github/actions/add_vendordep@main
#        with:
#          repo: Yet-Another-Software-Suite/vendor-json-repo
#          token: ${{ secrets.PUBLISH_VENDOR_JSON_TOKEN }}
#          vendordep_file: ${{ env.workingDirectory }}/build/maven/yams.json
#          pr_title: "Automatically add YAMS version ${{inputs.releaseVersion}}"
#          pr_branch: "publish_yams_${{inputs.releaseVersion}}"
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload vendordep json, maven repository, and javadocs
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.workingDirectory }}/build/maven/

  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
